version: '3.9'

services:
  frontend:
    profiles: ["prod"]
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
        - backend

  backend:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./storage:/storage

  # Development DB
  dev-db:
    profiles: ["dev"]
    image: ankane/pgvector
    restart: always
    ports:
      - "5433:5432"  # dev on 5433
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Production DB
  prod-db:
    profiles: ["prod"]
    image: ankane/pgvector
    restart: always
    ports:
      - "5434:5432"  # prod on 5434
    env_file:
      - .env.prod
    volumes:
      - prod_pgdata:/var/lib/postgresql/data

  pgadmin-dev:
    profiles: ["dev"]
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - dev-db


  pgadmin-prod:
    profiles: ["prod"]
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5051:80"
    env_file:
      - .env.prod
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - prod-db

  ollama:
    image: ollama/ollama
    privileged: true  # Required for GPU support (Linux)
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: |
      /bin/sh -c "
        ollama serve &  \
        sleep 2 && \
        ollama pull mistral:7b-instruct-q4_0 && \
        wait
      "
    restart: unless-stopped
    environment:
      - OLLAMA_LLM_LIBRARY=cuda_v11
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  pgdata:
  prod_pgdata:
  pgadmin_data:
  ollama_models:

